### ISSUE TITLE
日程与思源文档建立关联关系

### ISSUE THREAD

**Issue by RogerHuHu** [RogerHuHu/siyuan-plugin-schedule-manager#14]

**Comment by Timehsw** [comment]
非常需要这个功能，有些日程下，背后可以写一整篇文档，急需这个功能。

**Comment by Timehsw** [comment]
> 这个不一定能实现，思源的API里好像没提供这个功能，我再研究研究

非常感谢！！！

**Comment by RogerHuHu** [comment]
我目前有个想法，比较粗糙，思源块绑定和日程内容输入独立：
在日程内容输入框上面添加一个块ID绑定的输入框，然后再加个跳转按钮，点击跳转按钮，弹出对应块的悬浮窗

不知道这样能不能接受，跟思源自带编辑器那种超链接的方式暂时不知道怎么实现

**Comment by Timehsw** [comment]
这种实现方式也能满足需求，挺好的，作者更新好频繁，Thanks♪(･ω･)ﾉ。
