### ISSUE TITLE
新打开日程管理样式有问题

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#16]
新打开日程管理样式有问题
必须变更窗口大小才能显示正常
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/199e06d0-5d50-4441-9409-20f08c35ca92)

**Comment by jl0476** [comment]
另外，日历里面是白色字，看着比较清楚。看板里是黑色字，不是很清楚。
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/29a3b017-db66-4c01-a7a6-0c4870174206)
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/39ab4ba2-2500-4215-aba9-3640898b40fc)

**Comment by RogerHuHu** [comment]
好的，我晚点测试一下看

**Comment by jl0476** [comment]
> > 新打开日程管理样式有问题 必须变更窗口大小才能显示正常 ![image](https://user-images.githubusercontent.com/5226690/273809086-199e06d0-5d50-4441-9409-20f08c35ca92.png)
> > 这个问题我试了各种窗口大小，都没法复现，这个问题你那边必出吗？

嗯，思源v2.10.9 必出

**Comment by RogerHuHu** [comment]
> > > 新打开日程管理样式有问题 必须变更窗口大小才能显示正常 ![image](https://user-images.githubusercontent.com/5226690/273809086-199e06d0-5d50-4441-9409-20f08c35ca92.png)
> > > 这个问题我试了各种窗口大小，都没法复现，这个问题你那边必出吗？
> 
> 嗯，思源v2.10.9 必出

2.10.9之前的版本没问题，看群里好像说这个版本有bug，会影响很多插件，等更新看看

**Comment by RogerHuHu** [comment]
我在docker里面部署的，在浏览器上访问没问题，就桌面客户端有问题，默认高度变成0了，在改变窗口大小之后才会自适应，我先研究研究

**Comment by RogerHuHu** [comment]
v1.1.4中解决了这两个问题
