### ISSUE TITLE
将日程开启重复时，结束时间字段会丢失 时间部分。导致在更新任务状态的时候会报错(开始时间和结束时间是同一天，因为希望这是个日任务)

### ISSUE THREAD

**Issue by daijinp** [RogerHuHu/siyuan-plugin-schedule-manager#18]
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/77038509/b0aa2040-3f3f-4e34-80c7-43829ed68eab)

**Comment by daijinp** [comment]
感谢大佬的回复，无法手动设定时间。我发现开始时间和结束时间在一天就可以。我胡乱猜测：可能是由于验证的时候验证的是开始时间和结束时间的日期，因为我手动的在代码中添加了时区和时间页面上依然无法显示结束时间、并且无法更新状态
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/77038509/d977ea13-a423-48f3-9a90-df0598f91bad) 
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/77038509/1c609bd4-ccaf-4830-b956-972c7a6eca1c)

**Comment by RogerHuHu** [comment]
你是想实现一天内按小时的重复？目前重复周期选“日”的话，是以天为单位的，如果有这个需求，我尝试加一下

**Comment by daijinp** [comment]
我不是想要这个需求，但是这的确也是很好的一个产品设计。
整理一下上面的问题：我误以为只要选择了日重复就会一直重复下去没有重复的开始时间和结束时间，而开始时间和结束时间是单个任务的开始时间和结束时间。因为下面的现象：
选择开始时间为[2023.10.18 00:00:00 ~ 2023.10.25 ]时候，日历中会在18日~25日每天生成一个同样的任务，但在更新任意一个任务状态时所有任务状态都会被更新，所以我误以为这些天生成的是单个任务。
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/77038509/33fe4078-2c83-4555-bc53-2d2773f759fb)

**Comment by RogerHuHu** [comment]
重复任务视觉上会是一天一个，实际保存的记录就只有一个，那我先关了这个issue了，再开一个实现按小时重复的，然后看看能不能加提醒
