### ISSUE TITLE
日程管理保存后无显示以及一些其他问题

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#23]
1. 保存了重复个日程，日历视图无显示
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/963e4d8c-30fb-4419-80c2-bea128007cc1)
看板视图能够看到
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/709673ac-bfe8-4337-8ab7-b865abe2b07d)

2.看板视图全是 开始时间
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/80959e7c-3f1f-4871-9f3e-a2dea46f4d2c)

3. 结束时间我选择了时间，但是保存时只有日期
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/560f7863-36cb-44df-821f-6ad0c7ef4acc)

4. 日程内容中的两个输入框分别是什么作用，绿色剪头是做什么用的
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/e881ac9a-fac0-456d-9470-001b62103ca7)

5.请问全天任务现在如何配置？

**Comment by RogerHuHu** [comment]
1.我测试一下
2.复制的时候忘了改了
3.重复日程的结束时间只有日期，这个是Fullcalendar自带的功能，暂时不考虑改了
4.这块插件说明里提到了，上面的框是输入思源的块ID的（用于绑定思源的块），输完后，点击绿色箭头可以弹出对应块的悬浮窗，下面就是自己输入文字的
5.全天任务现在不支持，后面加一下

**Comment by jl0476** [comment]
> 1.重复日程开始时间和结束时间不要同一天，保存的时候右上角应该会有弹窗提示的，一天内的日程重复目前不支持 2.复制的时候忘了改了 3.重复日程的结束时间只有日期，这个是Fullcalendar自带的功能，暂时不考虑改了 4.这块插件说明里提到了，上面的框是输入思源的块ID的（用于绑定思源的块），输完后，点击绿色箭头可以弹出对应块的悬浮窗，下面就是自己输入文字的（后面优化下样式） 5.全天任务现在不支持，后面加一下

1.重复日程开始时间和结束时间不要同一天，保存的时候右上角应该会有弹窗提示的，一天内的日程重复目前不支持
这个没有提示，实际也保存上了。看板里面有这个数据，相关的日程文档里也有。

3.重复日程的结束时间只有日期，这个是Fullcalendar自带的功能，暂时不考虑改了
开始时间是不是也应该只有日期，统一样式。
结束时间是否可以不设置？

4.这块插件说明里提到了，上面的框是输入思源的块ID的（用于绑定思源的块），输完后，点击绿色箭头可以弹出对应块的悬浮窗，下面就是自己输入文字的（后面优化下样式）
后来看说明看到了，另外，绿色箭头点击时最好有个校验。没输入块或者找不到最好不要跳转。

5.全天任务现在不支持，后面加一下
麻烦了，感谢开发。

**Comment by jl0476** [comment]
另外：我看周视图里面有个all-day的栏目，跨天的日程是不是也放到这个里面比较合适？

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/0b6158d8-376b-4af2-adcb-584b28dc6d65)

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/ccaa999b-767c-4d26-bcd3-0bd9c74b2b58)

**Comment by RogerHuHu** [comment]
> > 1.重复日程开始时间和结束时间不要同一天，保存的时候右上角应该会有弹窗提示的，一天内的日程重复目前不支持 2.复制的时候忘了改了 3.重复日程的结束时间只有日期，这个是Fullcalendar自带的功能，暂时不考虑改了 4.这块插件说明里提到了，上面的框是输入思源的块ID的（用于绑定思源的块），输完后，点击绿色箭头可以弹出对应块的悬浮窗，下面就是自己输入文字的（后面优化下样式） 5.全天任务现在不支持，后面加一下
> 
> 1.重复日程开始时间和结束时间不要同一天，保存的时候右上角应该会有弹窗提示的，一天内的日程重复目前不支持 这个没有提示，实际也保存上了。看板里面有这个数据，相关的日程文档里也有。
> 
> 3.重复日程的结束时间只有日期，这个是Fullcalendar自带的功能，暂时不考虑改了 开始时间是不是也应该只有日期，统一样式。 结束时间是否可以不设置？
> 
> 4.这块插件说明里提到了，上面的框是输入思源的块ID的（用于绑定思源的块），输完后，点击绿色箭头可以弹出对应块的悬浮窗，下面就是自己输入文字的（后面优化下样式） 后来看说明看到了，另外，绿色箭头点击时最好有个校验。没输入块或者找不到最好不要跳转。
> 
> 5.全天任务现在不支持，后面加一下 麻烦了，感谢开发。

1.我测试一下
2.开始时间也是FullCalendar自带的，结束时间不设置有问题，比如想在一个月内每周一重复做一件事
4.我保存的时候先校验一下

**Comment by RogerHuHu** [comment]
> 另外：我看周视图里面有个all-day的栏目，跨天的日程是不是也放到这个里面比较合适？
> 
> ![image](https://user-images.githubusercontent.com/5226690/278528567-0b6158d8-376b-4af2-adcb-584b28dc6d65.png)
> 
> ![image](https://user-images.githubusercontent.com/5226690/278528614-ccaa999b-767c-4d26-bcd3-0bd9c74b2b58.png)

all-day 这里应该是放属性为全天的日程的，跨天的不一定的全天的，这个逻辑可能比较麻烦

**Comment by jl0476** [comment]
> > 另外：我看周视图里面有个all-day的栏目，跨天的日程是不是也放到这个里面比较合适？
> > ![image](https://user-images.githubusercontent.com/5226690/278528567-0b6158d8-376b-4af2-adcb-584b28dc6d65.png)
> > ![image](https://user-images.githubusercontent.com/5226690/278528614-ccaa999b-767c-4d26-bcd3-0bd9c74b2b58.png)
> 
> all-day 这里应该是放属性为全天的日程的，跨天的不一定的全天的，这个逻辑可能比较麻烦

我觉得可以分四部分
1. 先判断是不是跨天日程
1. 开始日期的当天 **开始时间** 是不是0:00
2. 结束日期的当天 **结束时间** 是不是24:00（控件里好像只能选到23:59:59）
3. 开始日期和结束日期**之间**的日期应该默认都是一天的

当然，如果能有全天日程，这个就不用这么麻烦的判断了。
现在没有全天日程，这个all-day好像并不能填入内容，我测试输入一个一天的00:00-23:59的日程，也不会呈现在上面栏位。

**Comment by RogerHuHu** [comment]
> > > 另外：我看周视图里面有个all-day的栏目，跨天的日程是不是也放到这个里面比较合适？
> > > ![image](https://user-images.githubusercontent.com/5226690/278528567-0b6158d8-376b-4af2-adcb-584b28dc6d65.png)
> > > ![image](https://user-images.githubusercontent.com/5226690/278528614-ccaa999b-767c-4d26-bcd3-0bd9c74b2b58.png)
> > 
> > 
> > all-day 这里应该是放属性为全天的日程的，跨天的不一定的全天的，这个逻辑可能比较麻烦
> 
> 我觉得可以分四部分
> 
> 1. 先判断是不是跨天日程
> 2. 开始日期的当天 **开始时间** 是不是0:00
> 3. 结束日期的当天 **结束时间** 是不是24:00（控件里好像只能选到23:59:59）
> 4. 开始日期和结束日期**之间**的日期应该默认都是一天的
> 
> 当然，如果能有全天日程，这个就不用这么麻烦的判断了。 现在没有全天日程，这个all-day好像并不能填入内容，我测试输入一个一天的00:00-23:59的日程，也不会呈现在上面栏位。

这些可能都要改FullCalendar源码，目前没精力，先把全天的加上去看看效果
