### ISSUE TITLE
新增日程颜色不正确

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#3]
默认字体和背景均为全白色，界面无法显示

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/99c889e8-9e66-4a47-b97e-fe32266506ce)

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/340c97c9-2de3-46d0-a05b-aa45b95f542d)

**Comment by RogerHuHu** [comment]
下个版本我默认改个其他颜色，不过建议给每个日程分类自定义颜色，方便区分，点击底下的颜色选择框就行。

**Comment by RogerHuHu** [comment]
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/3404169/2431456b-e0b1-4d0a-b442-32e26b4f5a69)
