### ISSUE TITLE
希望能在周或者日增加一个滑动选择时间之后自动弹出任务的输入框的功能

### ISSUE THREAD

**Issue by zhanghengyuan666** [RogerHuHu/siyuan-plugin-schedule-manager#30]
现在的时间选择有点繁琐，日期还好，但开始时间和结束时间需要一个个去选
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/44742816/69b5d7d0-7da5-4c58-97b8-91dd70fbb548)

**Comment by RogerHuHu** [comment]
这个我等第三方日历接入开发完之后再处理吧

**Comment by RogerHuHu** [comment]
本来想先做这个的，结果找了半天，没找到这个拖动选择时间后触发的回调，我得再研究研究

**Comment by RogerHuHu** [comment]
已经在 v1.3.0 中实现了
