### ISSUE TITLE
建议将[归档时间]和[日程分类]功能放入插件设置，而不是日历页面

### ISSUE THREAD

**Issue by musnows** [RogerHuHu/siyuan-plugin-schedule-manager#31]
首先对作者写出这个插件表达感谢和支持！下面提出我的一个小建议。

建议将[归档时间]和[日程分类]功能放入插件设置，而不是在日历页面显示；

我的日常使用中，一般习惯于将笔记本列表放在左侧展开，笔记本大纲（目录）放在右侧（因为之前obsidian就是这样的，已经习惯了）但此时左右两侧的面板会挤压中间的空间，导致日历显示的不完全，还出现了小部分按钮错位

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/87506951/4740fe60-6fcc-4ece-9eac-c9ef0ef7d5d8)

下图情况中，即便我已经将右侧的面版收起了，这里的`归档时间`依旧没有完整显示出来。

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/87506951/91e020ce-e094-4bf5-ad5c-891d2816f426)

个人认为，这两个按钮很影响整个日历面版视图的观感，而且由于显示不出来，在小屏幕笔记本上（截图所用的笔记本为13.3寸）使用这两个功能也非常不方便，你得把左边的笔记本列表也给折叠了才能完全显示。

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/87506951/eea5138e-9bac-43f2-9954-db06752ba29f)

把这两个功能放入插件设置中，感觉更加合理（如果有用户希望保持当前状态，也可以提供一个可选项让其在日历面板中按当前方式显示）；

**Comment by RogerHuHu** [comment]
我本来也准备单独弄一个设置界面，不过最近在整caldav，通过caldav可以把日程同步到手机自带APP，然后实现事件提醒

**Comment by musnows** [comment]
> 我本来也准备单独弄一个设置界面，不过最近在整caldav，通过caldav可以把日程同步到手机自带APP，然后实现事件提醒

这个功能也不错，但还是希望能先把插件在sy里面的使用搞好再去折腾外部的，同步到手机app得给不同厂家做适配吧？应该挺麻烦的。

**Comment by RogerHuHu** [comment]
> > 我本来也准备单独弄一个设置界面，不过最近在整caldav，通过caldav可以把日程同步到手机自带APP，然后实现事件提醒
> 
> 这个功能也不错，但还是希望能先把插件在sy里面的使用搞好再去折腾外部的，同步到手机app得给不同厂家做适配吧？应该挺麻烦的。

不用，都用Caldav协议导入，一般的手机的日历都支持的，不过主要最近事情比较多，没什么时候整这个，不然早就搞定了
![052BC187](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/3404169/44a36df9-1f48-4f79-bba7-73487fe21442)

**Comment by RogerHuHu** [comment]
这个问题我考虑了一下，左边的这些功能，单独放在一个界面不一定合适，我先临时弄一个隐藏按钮，点击按钮可以隐藏/显示左边的界面，这样如何

**Comment by musnows** [comment]
> 这个问题我考虑了一下，左边的这些功能，单独放在一个界面不一定合适，我先临时弄一个隐藏按钮，点击按钮可以隐藏/显示左边的界面，这样如何

可以的，感谢作者！😘😘😘😘

**Comment by RogerHuHu** [comment]
版本发布了，你等更新看看
