### ISSUE TITLE
日历功能增加类别，新建日程后重新打开思源，发现所有类别清空，但文件存在。

### ISSUE THREAD

**Issue by Kitem** [RogerHuHu/siyuan-plugin-schedule-manager#32]
如题，我在日历中新建新的类别去添加日程，然后重新打开思源笔记后发现都不见了，但类别和日程文件都在，好像就是读不到日历中，左侧类别里面也没有显示。我使用的系统是window11，不知道有没有什么关系。请各位大佬帮忙解惑！谢谢
![微信截图_20231118215319](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/25342879/efa54ef0-bf42-46a2-a406-df8f047c574a)

**Comment by RogerHuHu** [comment]
这个文档树看着不太对，日程管理笔记本下面的文档不要手动操作，插件解析的时候有固定的格式的，所有的操作都在插件界面内进行。你把TODO删了，或者移到其他笔记本下面，然后再新建一个分类看看

**Comment by Kitem** [comment]
您好，我是焕挺，您的邮件已经收到，我会尽快回复！

**Comment by RogerHuHu** [comment]
如果没有问题，我先把issue关了
