### ISSUE TITLE
查询笔记本失败

### ISSUE THREAD

**Issue by luommy** [RogerHuHu/siyuan-plugin-schedule-manager#34]
之前没有删除过日程管理笔记本，我卸了插件重新安装还是不行，思源版本2.11.3
希望作者早日修复~~
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/72240631/2ed28d5d-04aa-4eee-ad30-2275887d0822)

**Comment by RogerHuHu** [comment]
左侧的文档树方便截图看下吗，特别是跟日程管理笔记本相关的

**Comment by luommy** [comment]
文档树没有<日程笔记管理本>，我卸载后首次启动好像也没有自动创建：
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/72240631/0a1117a1-0a00-47ba-af66-cec342dee302)

**Comment by RogerHuHu** [comment]
我这边测试了2.11.4，可以正常创建，你那边方便打开开发者工具，然后开关下这个插件，看看Console输出的信息吗，或者可以尝试手动创建这个笔记本

**Comment by luommy** [comment]
- 开发者工具开关插件并没有输出
- 手动创建这个笔记本也是查询笔记本失败

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/72240631/537c6cd0-f2e7-4612-925f-e6583842aee9)

**Comment by luommy** [comment]
我应该知道了，问题是：我之前安装过这个插件，然后不用了，插件卸载后，这个<日程管理笔记本>被我关闭了；

后来切换了主题，新主题下鼠标不悬停在最下面不直接显示已关闭笔记本，我也不经常打开已关闭的笔记本，就给忘记了：）

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/72240631/6a12bbcf-46c6-42da-8ae5-f94a1a85d800)

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/72240631/1267f6d3-303a-451c-9554-42d8fd4627e9)

**Comment by luommy** [comment]
希望后面能增加暗黑模式~~

**Comment by RogerHuHu** [comment]
> 希望后面能增加暗黑模式~~

这段时间比较忙，刚一看，都一个多月没更新了，等空点了会增加深色主题的适配
