### ISSUE TITLE
月度重复实际与预期不符

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#35]
您好，我想建一个月度重复的任务，
如图，想要做一个每月16日的任务，
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/5221c2b6-d89f-4626-91a1-43add790bd9d)

结果建好了实际是按天重复。
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/8d399e20-fe1d-43d6-a2d4-293f4a6b0a90)

年度重复的任务没测试，麻烦一起看下

**Comment by jl0476** [comment]
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/ba6dd4a6-e562-41ab-933f-952389f4e9c5)
应该是这里没有赋值的原因，但是现在这个输入框是无法输入的状态，理论上应该是选择月中的一天

**Comment by RogerHuHu** [comment]
已修复，等更新
