### ISSUE TITLE
日周月视图无法更改

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#38]
![1709023176180_d](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/5f2f1578-02a5-47bb-b200-664cd5708cc1)

现在点击周、日、列表视图，无法切换，麻烦看下。

**Comment by RogerHuHu** [comment]
你是什么平台的客户端，PC？docker？

**Comment by jl0476** [comment]
> 你是什么平台的客户端，PC？docker？

PC

**Comment by jl0476** [comment]
Docker的也无法切换

**Comment by RogerHuHu** [comment]
我windows的客户端试了可以切换，docker的是不行，但是docker的看不出哪出问题了，你那边PC上方便打开开发者工具，看一下Console有没有输出吗

**Comment by jl0476** [comment]
> 我windows的客户端试了可以切换，docker的是不行，但是docker的看不出哪出问题了，你那边PC上方便打开开发者工具，看一下Console有没有输出吗

console没有任何输出

但是点击日程管理加载的时候有报错
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/e4562cbe-93a9-47f0-8e33-6f0f43445b57)

**Comment by RogerHuHu** [comment]
> > 我windows的客户端试了可以切换，docker的是不行，但是docker的看不出哪出问题了，你那边PC上方便打开开发者工具，看一下Console有没有输出吗
> 
> console没有任何输出
> 
> 但是点击日程管理加载的时候有报错 ![image](https://private-user-images.githubusercontent.com/5226690/308469730-e4562cbe-93a9-47f0-8e33-6f0f43445b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTA5NjMsIm5iZiI6MTcwOTExMDY2MywicGF0aCI6Ii81MjI2NjkwLzMwODQ2OTczMC1lNDU2MmNiZS05M2E5LTQ3ZjAtOGUzMy02ZjBmNDM0NDViNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg1NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmNTlkOTRhYzJlZWFiM2NjNDlmYTJiZjZmMjkyYTI4YmI1ZjEzMTU5ODJiNjdlZWJjMzhkNDdhMTQ0N2RlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g7AWt3da5tJt07dXMKJGTEuBwWjQ4bec6jzKChFXoRA)

跟我docker上一样的报错，但是很奇怪，我windows客户端没问题，我再找找看问题吧

**Comment by jl0476** [comment]
> > > 我windows的客户端试了可以切换，docker的是不行，但是docker的看不出哪出问题了，你那边PC上方便打开开发者工具，看一下Console有没有输出吗
> > 
> > 
> > console没有任何输出
> > 但是点击日程管理加载的时候有报错 ![image](https://private-user-images.githubusercontent.com/5226690/308469730-e4562cbe-93a9-47f0-8e33-6f0f43445b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTA5NjMsIm5iZiI6MTcwOTExMDY2MywicGF0aCI6Ii81MjI2NjkwLzMwODQ2OTczMC1lNDU2MmNiZS05M2E5LTQ3ZjAtOGUzMy02ZjBmNDM0NDViNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg1NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmNTlkOTRhYzJlZWFiM2NjNDlmYTJiZjZmMjkyYTI4YmI1ZjEzMTU5ODJiNjdlZWJjMzhkNDdhMTQ0N2RlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g7AWt3da5tJt07dXMKJGTEuBwWjQ4bec6jzKChFXoRA)
> 
> 跟我docker上一样的报错，但是很奇怪，我windows客户端没问题，我再找找看问题吧

是不是思源版本的问题
我是3.0.1

**Comment by RogerHuHu** [comment]
> > > > 我windows的客户端试了可以切换，docker的是不行，但是docker的看不出哪出问题了，你那边PC上方便打开开发者工具，看一下Console有没有输出吗
> > > 
> > > 
> > > console没有任何输出
> > > 但是点击日程管理加载的时候有报错 ![image](https://private-user-images.githubusercontent.com/5226690/308469730-e4562cbe-93a9-47f0-8e33-6f0f43445b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTA5NjMsIm5iZiI6MTcwOTExMDY2MywicGF0aCI6Ii81MjI2NjkwLzMwODQ2OTczMC1lNDU2MmNiZS05M2E5LTQ3ZjAtOGUzMy02ZjBmNDM0NDViNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg1NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmNTlkOTRhYzJlZWFiM2NjNDlmYTJiZjZmMjkyYTI4YmI1ZjEzMTU5ODJiNjdlZWJjMzhkNDdhMTQ0N2RlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g7AWt3da5tJt07dXMKJGTEuBwWjQ4bec6jzKChFXoRA)
> > 
> > 
> > 跟我docker上一样的报错，但是很奇怪，我windows客户端没问题，我再找找看问题吧
> 
> 是不是思源版本的问题 我是3.0.1

版本一样的

**Comment by RogerHuHu** [comment]
> > > > > 我windows的客户端试了可以切换，docker的是不行，但是docker的看不出哪出问题了，你那边PC上方便打开开发者工具，看一下Console有没有输出吗
> > > > 
> > > > 
> > > > console没有任何输出
> > > > 但是点击日程管理加载的时候有报错 ![image](https://private-user-images.githubusercontent.com/5226690/308469730-e4562cbe-93a9-47f0-8e33-6f0f43445b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTA5NjMsIm5iZiI6MTcwOTExMDY2MywicGF0aCI6Ii81MjI2NjkwLzMwODQ2OTczMC1lNDU2MmNiZS05M2E5LTQ3ZjAtOGUzMy02ZjBmNDM0NDViNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg1NzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VmNTlkOTRhYzJlZWFiM2NjNDlmYTJiZjZmMjkyYTI4YmI1ZjEzMTU5ODJiNjdlZWJjMzhkNDdhMTQ0N2RlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g7AWt3da5tJt07dXMKJGTEuBwWjQ4bec6jzKChFXoRA)
> > > 
> > > 
> > > 跟我docker上一样的报错，但是很奇怪，我windows客户端没问题，我再找找看问题吧
> > 
> > 
> > 是不是思源版本的问题 我是3.0.1
> 
> 版本一样的

![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/3404169/3d6eaf6b-536d-41a2-8aff-1d303d18ba56)
你在这里设置一下周一或周日起始，然后重新开关下插件试试

**Comment by jl0476** [comment]
好用了
