### ISSUE TITLE
新增日程后，保存并刷新后，在日历视图里见不到，在文档里有记录

### ISSUE THREAD

**Issue by HELIN007** [RogerHuHu/siyuan-plugin-schedule-manager#45]
你好，我建立了一个“工作”分类，在添加日程为“工作”时，添加完的时候可以在日历视图中查看到对应的日程，但是在保存刷新后，日历视图里面该条日程见不到了。已知，目前“工作”分类下共计60多条数据（再添加新数据不在日历视图里展示），另一个“家庭”分类共计3条（不存在这个现象），重新新建一个“工作2”后，新添日程为“工作2”不存在该现象，麻烦查看一下

**Comment by RogerHuHu** [comment]
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/3404169/147e038d-6c04-45de-97d5-61fbd7fcfc76)
可能是这个配置的问题，你现在的数量是多少

**Comment by HELIN007** [comment]
的确是，默认的64，修改为999之后就可以正常显示了！感谢提醒！
