### ISSUE TITLE
不能同步吗？

### ISSUE THREAD

**Issue by heartacker** [RogerHuHu/siyuan-plugin-schedule-manager#46]
谢谢，希望支持同步，不同电脑，同一个账号也不行

**Comment by RogerHuHu** [comment]
日程的数据是保存在日程管理笔记本里的文档中，文档同步就可以同步

**Comment by heartacker** [comment]
我试了很多遍，我这边并不是和你说的一样，我同步了。日程还是没有，分类还是空白。

> 日程的数据是保存在日程管理笔记本里的文档中，文档同步就可以同步

**Comment by RogerHuHu** [comment]
> 我试了很多遍，我这边并不是和你说的一样，我同步了。日程还是没有，分类还是空白。
> 
> > 日程的数据是保存在日程管理笔记本里的文档中，文档同步就可以同步

方便看下你这个笔记本里面下的文档吗（文档树就行）
![image](https://github.com/user-attachments/assets/c0f2d178-d329-4e49-ad40-5d14946f11fc)

**Comment by heartacker** [comment]
你的意思需要一个日程管理笔记本？

**Comment by RogerHuHu** [comment]
> 你的意思需要一个日程管理笔记本？

你的思源笔记里没有这个吗，这个是插件安装好之后默认建的，插件的文档里有说明

**Comment by heartacker** [comment]
我发现是有的，但是其实日历无法识别，我新建一个分类，然后就会有一个页面。
但是再次打开，并不是识别任何分类。
![image](https://github.com/user-attachments/assets/2f625375-6f67-4496-963d-a006a29c38ea)

**Comment by RogerHuHu** [comment]
> 我发现是有的，但是其实日历无法识别，我新建一个分类，然后就会有一个页面。 但是再次打开，并不是识别任何分类。 ![image](https://private-user-images.githubusercontent.com/1876302/353283277-2f625375-6f67-4496-963d-a006a29c38ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDkxMTIsIm5iZiI6MTcyMjMwODgxMiwicGF0aCI6Ii8xODc2MzAyLzM1MzI4MzI3Ny0yZjYyNTM3NS02ZjY3LTQ0OTYtOTYzZC1hMDA2YTI5YzM4ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDMwNjUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA3OTA4YjFjOGU1NjVkMzZlNDhiNmE5M2IzZGQzZTYyNmI3OGJiOTExOWIxYjQ0ZmI1MDk2YzZiMDNkMTA3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R76DkiG1Q2cvEq-wtaR5VUJ3tk6CmuX9kwfSdbgj3AQ)

![image](https://github.com/user-attachments/assets/88b3a34f-3596-424e-a916-db146094563b)
![image](https://github.com/user-attachments/assets/d7f561ee-30d7-48e0-b363-efc6828874c5)
先通过这两步打开控制台，然后再打开日历，看看是否有信息输出

**Comment by heartacker** [comment]
我发现日程里面，如有一些空白的页面，我把页面删除之后，

就好了。

之后每次日历创建一个分类，就会产生一个页面，
如果是手动添加一个页面，看起来就不行。
也许是需要在日历里面创建分类才行。

**Comment by heartacker** [comment]
而且创建最后，不能手动编辑。

**Comment by heartacker** [comment]
发现还是不行。
[127.0.0.1-1722315846950.log](https://github.com/user-attachments/files/16422279/127.0.0.1-1722315846950.log)

**Comment by heartacker** [comment]
111 是我在 日历中创建的。但是再次打开无法识别。

> 发现还是不行。 [127.0.0.1-1722315846950.log](https://github.com/user-attachments/files/16422279/127.0.0.1-1722315846950.log)

![image](https://github.com/user-attachments/assets/d593d22d-ff1a-40a2-9bba-d6b63d260013)

**Comment by heartacker** [comment]
默认 这个page，刚刚还可以，现在就不行了

**Comment by RogerHuHu** [comment]
> 默认 这个page，刚刚还可以，现在就不行了

要不加个QQ沟通一下？这里沟通比较费劲

**Comment by heartacker** [comment]
1014919474
