### ISSUE TITLE
Add i18n options?

### ISSUE THREAD

**Issue by rishacha** [RogerHuHu/siyuan-plugin-schedule-manager#47]
![image](https://github.com/user-attachments/assets/949ee325-e05a-411a-9342-ef03ab437568)

I liked the idea of the plugin a lot. I love the recurring tasks feature. Would it be possible to either merge your functionality with [this plugin](https://github.com/syh19/siyuan-plugin-task-list) or add better i18n support?

**Comment by RogerHuHu** [comment]
Thanks for your suggestion. There are great difficulties in merging with Task List Plugin, so I will not consider it at present, but I will try my best to optimize i18n support.

**Comment by rishacha** [comment]
@RogerHuHu  -  https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/blob/4f3991c6591b4f79ba68e053b8f54845b7af6232/src/components/Calendar.vue#L76C1-L77C1
Does the locale have to be hard-coded?

**Comment by rishacha** [comment]
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/2e4479bb-0adc-4b85-8a29-b30cae75ef82">

Adding the above option gives this, but the setting doesn't persist. Need your help with persistence.
