### ISSUE TITLE
Remove undefined in the task boxes

### ISSUE THREAD

**Issue by rishacha** [RogerHuHu/siyuan-plugin-schedule-manager#48]
![image](https://github.com/user-attachments/assets/3ec8ce21-8b60-4beb-812b-4e15fda9891d)

Is it possible to remove the undefined in the task box list for each day?

**Comment by rishacha** [comment]
I just installed the plugin and I see a lot of boxes showing up as undefined. Is it possible to remove them or add a better placeholder? `undefined` just looks ugly

**Comment by RogerHuHu** [comment]
Please show me the documents tree under the **Schedule Manager Notebook** notebook.

**Comment by rishacha** [comment]
![image](https://github.com/user-attachments/assets/25d74598-7106-40f6-b886-3c27453d8761)

**Comment by rishacha** [comment]
Any luck identifying the issue?

**Comment by rishacha** [comment]
I think this could be a cause - 

https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/blob/1166e4d621b48df67405402e71c44d7c95d061a3/src/components/Calendar.vue#L103C17-L126C18

**Comment by RogerHuHu** [comment]
> I think this could be a cause -
> 
> https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/blob/1166e4d621b48df67405402e71c44d7c95d061a3/src/components/Calendar.vue#L103C17-L126C18

Thank you, I tried it. Maybe my computer's system language is Chinese, so I can't reproduce your problem.
I have added a switch to decide whether to display the Chinese lunar calendar. You can update the plugin version to see if it solves the problem.
![image](https://github.com/user-attachments/assets/79c6c569-5712-4148-b78d-95b9b9138538)

**Comment by rishacha** [comment]
WORKS !!  Thank you !

@RogerHuHu - Can I raise some PRs for i18n though?

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/c63663b5-75ef-4e40-9c97-53602cfb11b3">
