### ISSUE TITLE
打扰一下，CalDav支持已经在开发计划中了吗

### ISSUE THREAD

**Issue by cwxsss** [RogerHuHu/siyuan-plugin-schedule-manager#49]
想问下开发者caldav预计在什么时间能开发，这样就可以日历工具集中到siyuan上面，再次感谢开发者做出的贡献，谢谢

**Comment by RogerHuHu** [comment]
这几个月一直事情比较多，之前尝试了一下，这个实现起来可能比较麻烦，时间上面无法保证，我只能尽量，不过之前几个issue挂着我自己也难受
![17B6A062](https://github.com/user-attachments/assets/042d1c4c-bd68-4398-bbab-742b6c05efc5)

**Comment by RogerHuHu** [comment]
目前已支持通过caldav订阅腾讯日历，但是目前仅支持获取3个月内的日程，且暂时只支持查看，后面会逐步更新功能
