### ISSUE TITLE
退出思源再打开后，日程和日历都丢失了

### ISSUE THREAD

**Issue by ZuoChenFttS** [RogerHuHu/siyuan-plugin-schedule-manager#51]
退出思源再打开后，日程和日历都丢失了。但是笔记本里还存在。
![image](https://github.com/user-attachments/assets/315d12e3-ee9f-4627-b27c-7f7ad81f3c2f)

Windows客户端 v3.1.3
插件版本v1.3.3

**Comment by RogerHuHu** [comment]
现在问题还存在吗，方便开发人员模式打开，然后再打开插件，看看输出

**Comment by ZuoChenFttS** [comment]
> 现在问题还存在吗，方便开发人员模式打开，然后再打开插件，看看输出
是这些吗？
![image](https://github.com/user-attachments/assets/31939441-4889-4af2-b060-3fe1a3a77514)
![image](https://github.com/user-attachments/assets/955032b0-c32f-443a-afa9-122a55c8f7be)

**Comment by RogerHuHu** [comment]
> > 现在问题还存在吗，方便开发人员模式打开，然后再打开插件，看看输出
> > 是这些吗？
> > ![image](https://private-user-images.githubusercontent.com/24040092/358914756-31939441-4889-4af2-b060-3fe1a3a77514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTYzMjIsIm5iZiI6MTcyMzk5NjAyMiwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5MTQ3NTYtMzE5Mzk0NDEtNDg4OS00YWYyLWIwNjAtM2ZlMWEzYTc3NTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE1NDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzAzNjU1NWJiOWVkNjhkN2NlMmVjOTc4MWExMjhjNWNiNmRlZDg1ZDE2ZTIzOTVmZWQxNjIwZjkwZDg2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5s8TrMbBSEN_LUFDZVQ44gSs8XTdw68E6LliOWvNrbw)
> > ![image](https://private-user-images.githubusercontent.com/24040092/358914766-955032b0-c32f-443a-afa9-122a55c8f7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTYzMjIsIm5iZiI6MTcyMzk5NjAyMiwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5MTQ3NjYtOTU1MDMyYjAtYzMyZi00NDNhLWFmYTktMTIyYTU1YzhmN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE1NDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDAyMmQ1OGY1ZThlYmE2NGExZWE4N2EzMzBkZDg3YjNkYzM1OTZkMmJkZTM3YTMxODY4NjNhNTdjNjExZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZakK16k-ceOVnbKWHBQHcx_Mv6KQr9bFokBo8VMUHNg)

日程管理笔记本下面的几个文档你手动修改过吗

**Comment by RogerHuHu** [comment]
#46 感觉你的问题跟这个issue比较像

**Comment by ZuoChenFttS** [comment]
> Quote reply
> Refer

应该是没改过，2个空的，一个应该也是默认内容如图：
![image](https://github.com/user-attachments/assets/f2e7a048-c9d7-42ae-9cb7-7c2990520d7e)

**Comment by RogerHuHu** [comment]
> > Quote reply
> > Refer
> 
> 应该是没改过，2个空的，一个应该也是默认内容如图： ![image](https://private-user-images.githubusercontent.com/24040092/358953704-f2e7a048-c9d7-42ae-9cb7-7c2990520d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA0MjUsIm5iZiI6MTcyNDIxMDEyNSwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5NTM3MDQtZjJlN2EwNDgtYzlkNy00MmFlLTljYjctN2MyOTkwNTIwZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTVlODFkMDIzZDY1YTY1MGNlMTc1ODc0MDVjNDI1M2U1NDI1NTMxOGVkNDNlOTk5MTMwOTgzYzc2NjE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H20efLNwOdMPAybo2AtJL-5pinajRCRIjnGP7uIaEKg)

不好意思，这两天事情比较多，麻烦设置项那边截图给我看看

**Comment by RogerHuHu** [comment]
> > > Quote reply
> > > Refer
> > 
> > 
> > 应该是没改过，2个空的，一个应该也是默认内容如图： ![image](https://private-user-images.githubusercontent.com/24040092/358953704-f2e7a048-c9d7-42ae-9cb7-7c2990520d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA0MjUsIm5iZiI6MTcyNDIxMDEyNSwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5NTM3MDQtZjJlN2EwNDgtYzlkNy00MmFlLTljYjctN2MyOTkwNTIwZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTVlODFkMDIzZDY1YTY1MGNlMTc1ODc0MDVjNDI1M2U1NDI1NTMxOGVkNDNlOTk5MTMwOTgzYzc2NjE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H20efLNwOdMPAybo2AtJL-5pinajRCRIjnGP7uIaEKg)
> 
> 不好意思，这两天事情比较多，麻烦设置项那边截图给我看看
![image](https://github.com/user-attachments/assets/f2dce0af-b23c-4e00-809d-4d86851fca9b)
可能这两个设置项要手动再设置一下

**Comment by ZuoChenFttS** [comment]
> > > > Quote reply
> > > > Refer
> > > 
> > > 
> > > 应该是没改过，2个空的，一个应该也是默认内容如图： ![image](https://private-user-images.githubusercontent.com/24040092/358953704-f2e7a048-c9d7-42ae-9cb7-7c2990520d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA0MjUsIm5iZiI6MTcyNDIxMDEyNSwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5NTM3MDQtZjJlN2EwNDgtYzlkNy00MmFlLTljYjctN2MyOTkwNTIwZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTVlODFkMDIzZDY1YTY1MGNlMTc1ODc0MDVjNDI1M2U1NDI1NTMxOGVkNDNlOTk5MTMwOTgzYzc2NjE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H20efLNwOdMPAybo2AtJL-5pinajRCRIjnGP7uIaEKg)
> > 
> > 
> > 不好意思，这两天事情比较多，麻烦设置项那边截图给我看看
> > ![image](https://private-user-images.githubusercontent.com/3404169/359737115-f2dce0af-b23c-4e00-809d-4d86851fca9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODIyODUsIm5iZiI6MTcyNDM4MTk4NSwicGF0aCI6Ii8zNDA0MTY5LzM1OTczNzExNS1mMmRjZTBhZi1iMjNjLTRlMDAtODA5ZC00ZDg2ODUxZmNhOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDI1OTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZkMWYxMDAzNDRiYzYwMjhjNzE2NDhkNDQ1ZjFlYjhkZDJjNjFlM2U5ZmY5YmExNTlmMmQyNzkyNzQ4ZGY4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HzfYygDDNgfrW5DDkdDS5YIAj_eQsmtmOJ2FkGW3OSU)
> > 可能这两个设置项要手动再设置一下

“日历语言设置”改成“简体中文”恢复正常了，之前不知道为啥这个值是“1”。

> > > > Quote reply
> > > > Refer
> > > 
> > > 
> > > 应该是没改过，2个空的，一个应该也是默认内容如图： ![image](https://private-user-images.githubusercontent.com/24040092/358953704-f2e7a048-c9d7-42ae-9cb7-7c2990520d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA0MjUsIm5iZiI6MTcyNDIxMDEyNSwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5NTM3MDQtZjJlN2EwNDgtYzlkNy00MmFlLTljYjctN2MyOTkwNTIwZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTVlODFkMDIzZDY1YTY1MGNlMTc1ODc0MDVjNDI1M2U1NDI1NTMxOGVkNDNlOTk5MTMwOTgzYzc2NjE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H20efLNwOdMPAybo2AtJL-5pinajRCRIjnGP7uIaEKg)
> > 
> > 
> > 不好意思，这两天事情比较多，麻烦设置项那边截图给我看看
> > ![image](https://private-user-images.githubusercontent.com/3404169/359737115-f2dce0af-b23c-4e00-809d-4d86851fca9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTU3NTYsIm5iZiI6MTcyNDM5NTQ1NiwicGF0aCI6Ii8zNDA0MTY5LzM1OTczNzExNS1mMmRjZTBhZi1iMjNjLTRlMDAtODA5ZC00ZDg2ODUxZmNhOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDY0NDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgwNmIxOTgxOWI4MjFmNzUwMmZhZjFlMTQ1YmVhYTRkMzk5Njg3YWM4ZDc4NGMyYmZhYzRjMWE5MjJiMjM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hV8K2bXyu5b_WFWP7QRlMUwSoLoVxIa859sbm3dzCnM)
> > 可能这两个设置项要手动再设置一下

“历史语言设置”这里原来是“1”，改成“简体中文”就恢复正常了，“1”没来的截图，现在复现不了啦。

**Comment by RogerHuHu** [comment]
> > > > > Quote reply
> > > > > Refer
> > > > 
> > > > 
> > > > 应该是没改过，2个空的，一个应该也是默认内容如图： ![image](https://private-user-images.githubusercontent.com/24040092/358953704-f2e7a048-c9d7-42ae-9cb7-7c2990520d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA0MjUsIm5iZiI6MTcyNDIxMDEyNSwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5NTM3MDQtZjJlN2EwNDgtYzlkNy00MmFlLTljYjctN2MyOTkwNTIwZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTVlODFkMDIzZDY1YTY1MGNlMTc1ODc0MDVjNDI1M2U1NDI1NTMxOGVkNDNlOTk5MTMwOTgzYzc2NjE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H20efLNwOdMPAybo2AtJL-5pinajRCRIjnGP7uIaEKg)
> > > 
> > > 
> > > 不好意思，这两天事情比较多，麻烦设置项那边截图给我看看
> > > ![image](https://private-user-images.githubusercontent.com/3404169/359737115-f2dce0af-b23c-4e00-809d-4d86851fca9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODIyODUsIm5iZiI6MTcyNDM4MTk4NSwicGF0aCI6Ii8zNDA0MTY5LzM1OTczNzExNS1mMmRjZTBhZi1iMjNjLTRlMDAtODA5ZC00ZDg2ODUxZmNhOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDI1OTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZkMWYxMDAzNDRiYzYwMjhjNzE2NDhkNDQ1ZjFlYjhkZDJjNjFlM2U5ZmY5YmExNTlmMmQyNzkyNzQ4ZGY4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HzfYygDDNgfrW5DDkdDS5YIAj_eQsmtmOJ2FkGW3OSU)
> > > 可能这两个设置项要手动再设置一下
> 
> “日历语言设置”改成“简体中文”恢复正常了，之前不知道为啥这个值是“1”。
> 
> > > > > Quote reply
> > > > > Refer
> > > > 
> > > > 
> > > > 应该是没改过，2个空的，一个应该也是默认内容如图： ![image](https://private-user-images.githubusercontent.com/24040092/358953704-f2e7a048-c9d7-42ae-9cb7-7c2990520d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTA0MjUsIm5iZiI6MTcyNDIxMDEyNSwicGF0aCI6Ii8yNDA0MDA5Mi8zNTg5NTM3MDQtZjJlN2EwNDgtYzlkNy00MmFlLTljYjctN2MyOTkwNTIwZDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAzMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYTVlODFkMDIzZDY1YTY1MGNlMTc1ODc0MDVjNDI1M2U1NDI1NTMxOGVkNDNlOTk5MTMwOTgzYzc2NjE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H20efLNwOdMPAybo2AtJL-5pinajRCRIjnGP7uIaEKg)
> > > 
> > > 
> > > 不好意思，这两天事情比较多，麻烦设置项那边截图给我看看
> > > ![image](https://private-user-images.githubusercontent.com/3404169/359737115-f2dce0af-b23c-4e00-809d-4d86851fca9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTU3NTYsIm5iZiI6MTcyNDM5NTQ1NiwicGF0aCI6Ii8zNDA0MTY5LzM1OTczNzExNS1mMmRjZTBhZi1iMjNjLTRlMDAtODA5ZC00ZDg2ODUxZmNhOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDY0NDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgwNmIxOTgxOWI4MjFmNzUwMmZhZjFlMTQ1YmVhYTRkMzk5Njg3YWM4ZDc4NGMyYmZhYzRjMWE5MjJiMjM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hV8K2bXyu5b_WFWP7QRlMUwSoLoVxIa859sbm3dzCnM)
> > > 可能这两个设置项要手动再设置一下
> 
> “历史语言设置”这里原来是“1”，改成“简体中文”就恢复正常了，“1”没来的截图，现在复现不了啦。

这个应该是我异常值判断没做好

**Comment by nypyp** [comment]
请问我同样的问题，改了简体中文保存后仍然会自动跳到1是为什么？

**Comment by RogerHuHu** [comment]
> 请问我同样的问题，改了简体中文保存后仍然会自动跳到1是为什么？

你好，方便截图看看吗
