### ISSUE TITLE
添加插件后没有反应

### ISSUE THREAD

**Issue by eliza-rina** [RogerHuHu/siyuan-plugin-schedule-manager#52]
添加完插件后，自动增加了笔记本，但笔记本下什么都没有。也没有找到任何的日历，不知道怎么用
![image](https://github.com/user-attachments/assets/e2e5da27-6130-47a5-ac6d-2a9b658572d1)

**Comment by RogerHuHu** [comment]
> 添加完插件后，自动增加了笔记本，但笔记本下什么都没有。也没有找到任何的日历，不知道怎么用 ![image](https://private-user-images.githubusercontent.com/32827409/365706042-e2e5da27-6130-47a5-ac6d-2a9b658572d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDM3ODEsIm5iZiI6MTcyNTk0MzQ4MSwicGF0aCI6Ii8zMjgyNzQwOS8zNjU3MDYwNDItZTJlNWRhMjctNjEzMC00N2E1LWFjNmQtMmE5YjY1ODU3MmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA0NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYWYxZWE2NTVkYzJmZGRhYTMwNTBiODU0NjE4ZjEyNTdkMjQ1ZjYxMTY0ZGQ4NGNjZmI3ZGYzNTRlY2ZhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xBUt7Ypk9F22HhHGhNg3VHPdkkIaE6NO9eXk9SoRFzU)

![image](https://github.com/user-attachments/assets/33a052a4-b80f-4c88-85b2-e408f02d345b)
上方工具栏会有个图标（我用的主题里是在右侧），点击图标才会打开插件，这个笔记本下是建了日程分类之后才会有东西
