### ISSUE TITLE
新建“日程分类”，重新进入后，就变成白板了，日历也没了。

### ISSUE THREAD

**Issue by wangfeiwu555** [RogerHuHu/siyuan-plugin-schedule-manager#53]
![局部截取_20240912_133330](https://github.com/user-attachments/assets/d710cf8e-63da-45b2-84b5-86c4c90593ac)
![局部截取_20240912_133348](https://github.com/user-attachments/assets/57240d0a-070a-4a73-bbeb-f00c2b908695)
新建“日程分类”，重新进入后，就变成白板了，日历也没了。

**Comment by wangfeiwu555** [comment]
有没大神指点一下

**Comment by RogerHuHu** [comment]
> 有没大神指点一下

可能需要到设置界面，手动设置一下语言
