### ISSUE TITLE
日历 看板bug，日历 及 所有日程都看不到

### ISSUE THREAD

**Issue by holduan** [RogerHuHu/siyuan-plugin-schedule-manager#55]
好几次了，删了插件重新添加日程，没多久又出现，不记得是不是关闭日历管理界面后新打开就出现这问题。
日程笔记本下的标签文档没有动过
思源 3.1.6，插件最新版

![image](https://github.com/user-attachments/assets/f5d8b7ba-ea60-410f-b3c5-22aaff6dbc36)

https://github.com/user-attachments/assets/5fa72dbd-5fa7-482b-9e54-381f9619acdf

**Comment by RogerHuHu** [comment]
设置界面的语言那里手动设置一下，有个bug，最近在出差还没时间修

**Comment by holduan** [comment]
> 设置界面的语言那里手动设置一下，有个bug，最近在出差还没时间修

可以了，谢谢提醒 ❤

**Comment by RogerHuHu** [comment]
> > 设置界面的语言那里手动设置一下，有个bug，最近在出差还没时间修
> 
> 可以了，谢谢提醒 ❤

不客气，应该的！
