### ISSUE TITLE
macos 端的日历和看板信息均不显示

### ISSUE THREAD

**Issue by ZhenglongChen-code** [RogerHuHu/siyuan-plugin-schedule-manager#56]
<img width="890" alt="截屏2024-09-25 01 02 30" src="https://github.com/user-attachments/assets/cb497c80-1497-4c20-821a-e298b66fefcc">

这个日历是空白，还有就是下面看板上的信息也都不显示

<img width="858" alt="截屏2024-09-25 01 03 39" src="https://github.com/user-attachments/assets/ffe04ad5-b61f-459b-917b-6dd394ba31e9">

**Comment by RogerHuHu** [comment]
#55 应该也是这个问题，我马上修复一下
