### ISSUE TITLE
日程管理按钮不显眼

### ISSUE THREAD

**Issue by flyingnight** [RogerHuHu/siyuan-plugin-schedule-manager#59]
日程管理按钮是在插件按钮中间的，每次打开要去插件中找，很麻烦，希望可以将按钮放到顶部左边的菜单栏里，就和同步那一行边上。
![image](https://github.com/user-attachments/assets/fbb1048a-4433-4051-9818-35b288010753)
本来我想将 日程管理 页钉住，后来发现钉住的 日程管理页 在笔记重建索引和刷新时，会自动取消钉住。

**Comment by RogerHuHu** [comment]
刚看了一下，我可以放在左边那一块，但是图标显示的顺序是思源控制的，插件没办法控制这个图标显示的准确位置

**Comment by flyingnight** [comment]
> 左边那个日历的图标是什么功能？这个插件的图标跟它重了

那是一个日记插件，可以显示一个小日历，检测到当天有日记会有标点，可以直接选中创建那一天的日记

**Comment by flyingnight** [comment]
> 刚看了一下，我可以放在左边那一块，但是图标显示的顺序是思源控制的，插件没办法控制这个图标显示的准确位置

我找到一个插件可以调节这些按钮的位置，不过还是建议可以把这个图标位置默认放在左边那里，别的插件有做到，应该是有方法可以实现这个

**Comment by RogerHuHu** [comment]
我看看能不能实现自己配置图标显示的区域，因为有的人可能习惯了在右边

**Comment by flyingnight** [comment]
> 我看看能不能实现自己配置图标显示的区域，因为有的人可能习惯了在右边

已经有插件可以实现更改图标位置了，不用再添加更改位置的功能了

**Comment by RogerHuHu** [comment]
> > 我看看能不能实现自己配置图标显示的区域，因为有的人可能习惯了在右边
> 
> 已经有插件可以实现更改图标位置了，不用再添加更改位置的功能了

好的好的，那我把issue关了
