### ISSUE TITLE
集市无法更新

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#6]
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/f0296354-1724-4eba-ab3d-7380162360d9)

**Comment by RogerHuHu** [comment]
这个我也不知道为什么，只有插件市场里面才能更新，难道是我上传的包的问题？

**Comment by jl0476** [comment]
![image](https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/6bf23adc-1da3-41db-bd3b-8fa065eb1126)
1017854502   这个群里有不少的插件开发者，看看是不是一起交流下

**Comment by RogerHuHu** [comment]
我也在这个群里，不过我已经给思源提issue了，先看看D大他们怎么说吧

**Comment by RogerHuHu** [comment]
问题找到了，是我plugin.json里面，url填错了，多了.git后缀

**Comment by jl0476** [comment]
还是有问题，现在已下载界面不显示更新。
还是得到插件页面更新。

**Comment by RogerHuHu** [comment]
我自己也是，也跟其他插件对比过，不知道问题出在哪里，我在这里提了issue。https://github.com/siyuan-note/bazaar/issues/1256

**Comment by RogerHuHu** [comment]
更新了一版，试了可以从已安装插件列表里更新了，就先关这个issue了
