### ISSUE TITLE
点击已有日程后新建日程响应不正确

### ISSUE THREAD

**Issue by jl0476** [RogerHuHu/siyuan-plugin-schedule-manager#7]
刚进入界面可以新建日程，
但是点击以后日程之后，再新建日程就会读取已有日程的数据，并且无法保存
具体参考录屏

https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/d39043d9-d1d8-4826-a908-3f4e8773ef2c

**Comment by RogerHuHu** [comment]
这个我刚才测试了，是分类选择的问题，界面保留了上次填写的信息，但是没有触发分类选中的事件，重新选择下分类就可以了，我下个版本解决

**Comment by jl0476** [comment]
只有一个分类，没法重新选择

**Comment by RogerHuHu** [comment]
直接点一下当前分类就行，触发了选中事件就可以

**Comment by jl0476** [comment]
另外取消勾选左侧的分类，右侧的日历面板并不会刷新

**Comment by RogerHuHu** [comment]
现在这个功能没做，涉及到数据重新加载，现在的代码有点乱，后面代码整理完之后再做这个功能

**Comment by jl0476** [comment]
> 直接点一下当前分类就行，触发了选中事件就可以

没明白怎么操作，我点击了右侧的分类。在创建的日程的页面也切换了分类。
均无效，等你更新吧。

**Comment by jl0476** [comment]
> 直接点一下当前分类就行，触发了选中事件就可以

@RogerHuHu 最新版本的，还是会出现这个问题。
如果不点击取消按钮，直接点击其他地方收起面板就会复现。





https://github.com/RogerHuHu/siyuan-plugin-schedule-manager/assets/5226690/83cf4d9d-3b55-4282-a968-d0a3f4bdbb6e

**Comment by RogerHuHu** [comment]
可以参考 v1.0.6 的发布日志，我是故意这么实现的，防止编辑日程信息的时，不小心点到其他地方，编辑界面关闭了，之前填写的信息就丢失了
